### ISSUE TITLE
Meiryo 6.50の対応

### ISSUE THREAD

**Issue by eai04191** [meir000/MeiryoKe#1]
TL;DR: 現在のWindows 10の最新バージョン(2004 ビルド19041.329)ではメイリオのバージョンは6.50となっています。このバージョンにパッチを当てられるmeiryoKe_genをリリースしていただけませんか？

長らくMeiryoKeにはWindoowsでコーディングをする際に大変お世話になっています。
先日Windoows 10を再インストールしたのですが、その際にMeiryoKeのバックアップをとるのを忘れてしまいました。
meiryoKe_gen_6.30rev5で作成しようとしたのですが、最新のメイリオ6.50とはハッシュが合わず作成できませんでした。今はしょうがないので他のフォントを使っていますが、やはりMeiryoKeが一番に思えます。
どうかメイリオ6.50に対応していただけませんか？

**Comment by meir000** [comment]
メイリオのバージョンアップに気づいておらず助かりました。ありがとうございます。
6.50rev1をリリースしました。
