### ISSUE TITLE
Meiryo 6.51ベース

### ISSUE THREAD

**Issue by nicodegu** [meir000/MeiryoKe#2]
Windows 11 でも 6.50rev1 で快適に MeiryoKe を使わせて頂いていましたが、Windows を起動している状態で Windows 11 ブータブルメディアにて上書きインストールをしたところ、各ソフトウェアで MeiryoKe が使用できなくなっていました。

メイリオのバージョンを調べますと 6.51 となっていました。
これに対応した生成ツールをリリースして頂けないでしょうか。

MeiryoKe なしでは何をするにも辛いです。

**Comment by meir000** [comment]
メイリオが新バージョンになっている事に気付いていなかったので助かります。
ありがとうございます。
早速 6.51対応版をリリースいたしました。
他にも何かお気付きの点があれば また教えてください。

**Comment by nicodegu** [comment]
こんなに早くリリースしていただけて感謝です。
お陰様で MeiryoKe が帰ってきました！
本当にありがとうございました。
