### ISSUE TITLE
MeiryoKe_Console Bold で、特定サイズで `i` が 判別不能になる

### ISSUE THREAD

**Issue by KSR-Yasuda** [meir000/MeiryoKe#4]
`MeiryoKe_Console` の Bold で、特定のサイズになると、
小文字の `i` (アイ) が 潰れて、判別不能になります。

![MeiryoKe_Console_20230310_123833](https://user-images.githubusercontent.com/31273423/224218878-56092788-5474-4c6e-8f07-b0c4ef43719e.png)

Regular だと、問題ないようで、Bold特有 の問題です。

![MeiryoKe_Console_20230310_124006](https://user-images.githubusercontent.com/31273423/224218214-6f359ca3-0ab8-4b88-b4bd-16e8169e549d.png)

また、`MeiryoKe_Gothic` だと 問題ないようです。

こちら、改善できないでしょうか？
さすがに 字形が崩れすぎていて、`l` (エル) かと、ぎょっとしました。

* `MeiryoKe_Console` v6.50+rev1

**Comment by meir000** [comment]
若干調整して 6.50rev2, 6.51rev2 をリリースしました。
フォントサイズやレンダラーによっては まだ上下が付いてしまう場合もあり、
確実に直っているか分かりませんが 試してみてください。

**Comment by KSR-Yasuda** [comment]
ありがとうございます。
v6.50+rev2 で、改善していること を確認しました。
![MeiryoKe_20230313_090537](https://user-images.githubusercontent.com/31273423/224582471-7b0d5131-ce2a-45db-a55c-49a716393809.png)
